### ISSUE TITLE
Erro quando lista vazia

### ISSUE THREAD

**Issue by rodrigoccurvo** [rafatieppo/lucylattes#3]
Aparentemente o script não lida com o caso em que uma das lista de publicacoes está vazia:

```Traceback (most recent call last):
  File "lucyLattes.py", line 64, in <module>
    gettidydf()
  File "lucylattes/tidydf.py", line 104, in gettidydf
    dfpaper['ID'] = np.concatenate(lsid)
ValueError: need at least one array to concatenate```

**Comment by rafatieppo** [comment]
Este é um erro (deficiência) antigo do código. Esta falha ficou porque usualmente os currículos analisados tem dados para serem extraídos . Vou deixar a "issue" aberta, quando possível tentarei melhorar. 

Como sugestão, caso tenha  currículos com poucos dados, adicione pelo menos um currículo mais "completo" para preencher as "listas".

Obrigado pelo comentário.
