### ISSUE TITLE
grapho.py :: Empty DataFrame[]

### ISSUE THREAD

**Issue by augustgs** [rafatieppo/lucylattes#8]
quando chama a função getgrapho() ele pesquisa em um dataframe que aparentemente está vazio.

Segue abaixo o reply do erro:

```
[1 rows x 9 columns]
--------------------------------------------------------
                  ID  ...                             ADDRESS_ENTERP
28  7829435808451741  ...  Universidade Federal do Rio Grande do Sul

[1 rows x 9 columns]
--------------------------------------------------------
Empty DataFrame
Columns: [ID, FULL_NAME, LAST_NAME, CITADO, CITY, STATE, RESUME, UPDATE, ADDRESS_ENTERP]
Index: []
--------------------------------------------------------
Traceback (most recent call last):
  File "lucyLattes.py", line 68, in <module>
    getgrapho()
  File "/home/---/Área de Trabalho/---/doutorado/projeto/lucylattes-master/grapho.py", line 103, in getgrapho
    lname = lname.iloc[0, 1]
  File "/home/---/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/home/---/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/indexing.py", line 2143, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/---/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/indexing.py", line 223, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/---/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/indexing.py", line 2070, in _validate_key
    self._validate_integer(key, axis)
  File "/home/---/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/indexing.py", line 2139, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by rafatieppo** [comment]
Qual a versão que vc está usando?
Pfv, no arquivo `list_id_name.txt`, verifique se há algum espaço entre characters abaixo da linha 4
